### ISSUE TITLE
Failure to connect

### ISSUE THREAD

**Issue by CliffS** [AlCalzone/node-coap-client#18] opened 2017-11-05 15:56 UTC
Hi

Thanks for the better documentation, it was a great help.

The current problem is that after a while, `Coap.tryToConnect(url)` is failing, returning `false`.  I realised after a while that leaving observers running whilst terminating the program was exacerbating the issue, so I now have:
```javascript
process.on('exit', () => {
  console.log('Cleaning up...');
  Coap.reset();
});

process.on('SIGINT', function() {
  process.exit();
});

process.on('SIGTERM', function() {
  process.exit();
});

process.on('uncaughtException', (err) => {
  console.log('Cleaning up for exception');
  Coap.reset();
  throw err;
});
```

I think this covers all exit routes and should cancel any `observe`s.  Nevertheless, after a while, I find I cannot connect to the Trådfri gateway without physically resetting it.  If I leave a program running, eventually it stops `observe`ing and then I cannot reconnect.

Three questions:

1. Is there anything else I should be doing? 
1. Is it a bug or memory leak in the Trådfri gateway causing it?
1. Is there anyway to do a periodic remote reset on the gateway?

Many thanks.

**Comment by AlCalzone** [comment] 2017-11-06 07:45
As per the CoAP RFC it should not be necessary to unregister observers on the server/gateway because it should stop responding and "forget" the client after a few failed attempts or if the client rejects the response.
However it might be that the gateway is not handling that correctly.

I'll add a method to explicitly deregister observers from the gateway and let you know so you can test.

**Comment by AlCalzone** [comment] 2017-11-14 18:00
I failed to reproduce your issue. Can you try to provide some code or steps to reliably reproduce the problem? 
What I did:
* connect to the gateway using a previously stored identity/psk pair
* set up an observer
* immediately stop the process with `process.exit` and restart it

**Comment by CliffS** [comment] 2017-11-14 18:11
> Can you try to provide some code or steps to reliably reproduce the problem?

Nope.  I scrapped the code in favour of your `node-tradfri-client` code.  Your code seems to work on the latest version of the software so let's assume that either Ikea fixed it or you did. :)

BTW, thanks for all your hard work on this.  I very much appreciate it.

**Comment by AlCalzone** [comment] 2017-11-15 07:15
Great, closing

**Closed by AlCalzone** 2017-11-15 07:15 UTC
